=== hazelcast/hazelcast-nodejs-client/test/unit/config/configurations/config-schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "title": "Hazelcast Node.js Client Configuration",
    "type": "object",
    "definitions": {
        "propertiesObject": {
            "type": "object",
            "propertyNames": {
                "pattern": "^[^ ]*$"
            },
            "additionalProperties": {
                "type": [
                    "number",
                    "string",
                    "boolean"
                ]
            }
        },
        "positiveInteger": {
            "type": "number",
            "minimum": 0,
            "multipleOf": 1
        }
    },
    "properties": {
        "clusterName": {
            "type": [
                "string",
                "null"
            ]
        },
        "instanceName": {
            "type": [
                "string",
                "null"
            ]
        },
        "properties": {
            "$ref": "#/definitions/propertiesObject"
        },
        "clientLabels": {
            "type": "array",
            "uniqueItems": true,
            "items": {
                "type": "string"
            }
        },
        "network": {
            "type": "object",
            "properties": {
                "clusterMembers": {
                    "type": "array",
                    "minItems": 1,
                    "uniqueItems": true,
                    "items": {
                        "type": "string"
                    }
                },
                "redoOperation": {
                    "type": "boolean",
                    "default": false
                },
                "smartRouting": {
                    "type": "boolean",
                    "default": true
                },
                "connectionTimeout": {
                    "type": "number",
                    "minimum": 1000,
                    "default": 5000
                },
                "hazelcastCloud": {
                    "type": "object",
                    "properties": {
                        "discoveryToken": {
                            "type": [
                                "string",
                                "null"
                            ]
                        }
                    }
                },
                "ssl": {
                    "type": "object",
                    "properties": {
                        "enabled": {
                            "type": "boolean",
                            "default": false
                        },
                        "sslOptions": {
                            "anyOf": [
                                {
                                    "type": "object",
                                    "properties": {
                                        "properties": {
                                            "$ref": "#/definitions/propertiesObject"
                                        }
                                    }
                                },
                                {
                                    "type": "null"
                                }
                            ]
                        },
                        "sslOptionsFactoryProperties": {
                            "$ref": "#/definitions/propertiesObject"
                        }
                    }
                }
            }
        },
        "backupAckToClientEnabled": {
            "type": "boolean",
            "default": true
        },
        "connectionStrategy": {
            "type": "object",
            "properties": {
                "asyncStart": {
                    "type": "boolean",
                    "default": false
                },
                "reconnectMode": {
                    "enum": [
                        "on",
                        "off",
                        "async"
                    ]
                },
                "connectionRetry": {
                    "type": "object",
                    "properties": {
                        "initialBackoffMillis": {
                            "type": "number",
                            "minimum": 0
                        },
                        "maxBackoffMillis": {
                            "type": "number",
                            "minimum": 0
                        },
                        "multiplier": {
                            "type": "number",
                            "minimum": 1
                        },
                        "clusterConnectTimeoutMillis": {
                            "type": "number"
                        },
                        "jitter": {
                            "type": "number",
                            "minimum": 0,
                            "maximum": 1
                        }
                    }
                }
            }
        },
        "serialization": {
            "type": "object",
            "properties": {
                "defaultNumberType": {
                    "enum": [
                        "double",
                        "short",
                        "integer",
                        "float",
                        "byte",
                        "long"
                    ],
                    "default": "double"
                },
                "jsonStringDeserializationPolicy": {
                    "enum": [
                        "eager",
                        "no_deserialization"
                    ],
                    "default": "eager"
                },
                "isBigEndian": {
                    "type": "boolean",
                    "default": false
                },
                "portableVersion": {
                    "$ref": "#/definitions/positiveInteger"
                }
            }
        },
        "nearCaches": {
            "type": "object",
            "patternProperties": {
                ".+": {
                    "type": "object",
                    "properties": {
                        "invalidateOnChange": {
                            "type": "boolean",
                            "default": true
                        },
                        "maxIdleSeconds": {
                            "type": "number",
                            "default": 0,
                            "minimum": 0
                        },
                        "inMemoryFormat": {
                            "enum": [
                                "object",
                                "binary"
                            ],
                            "default": "binary"
                        },
                        "timeToLiveSeconds": {
                            "type": "number",
                            "minimum": 0,
                            "default": 0
                        },
                        "evictionPolicy": {
                            "enum": [
                                "none",
                                "lru",
                                "lfu",
                                "random"
                            ],
                            "default": "none"
                        },
                        "evictionMaxSize": {
                            "$ref": "#/definitions/positiveInteger",
                            "default": "maximum safe integer"
                        },
                        "evictionSamplingCount": {
                            "$ref": "#/definitions/positiveInteger",
                            "default": 8
                        },
                        "evictionSamplingPoolSize": {
                            "$ref": "#/definitions/positiveInteger",
                            "default": 16
                        }
                    }
                }
            }
        },
        "reliableTopics": {
            "type": "object",
            "patternProperties": {
                ".+": {
                    "type": "object",
                    "properties": {
                        "readBatchSize": {
                            "$ref": "#/definitions/positiveInteger",
                            "default": 25
                        },
                        "overloadPolicy": {
                            "enum": [
                                "discard_oldest",
                                "discard_newest",
                                "block",
                                "error"
                            ],
                            "default": "block"
                        }
                    }
                }
            }
        },
        "flakeIdGenerators": {
            "type": "object",
            "patternProperties": {
                ".+": {
                    "type": "object",
                    "properties": {
                        "prefetchCount": {
                            "$ref": "#/definitions/positiveInteger",
                            "default": 100
                        },
                        "prefetchValidityMillis": {
                            "$ref": "#/definitions/positiveInteger",
                            "default": 600000
                        }
                    }
                }
            }
        },
        "loadBalancer": {
            "type": "object",
            "properties": {
                "type": {
                    "enum": [
                        "round_robin",
                        "random"
                    ]
                }
            }
        }
    }
}

=== hazelcast/hazelcast-nodejs-client/test/config/configurations/full.json
{
    "clusterName": "testCluster",
    "instanceName": "clientName",
    "properties": {
        "hazelcast.client.heartbeat.interval": 1000,
        "hazelcast.client.heartbeat.timeout": 10000,
        "hazelcast.client.invocation.retry.pause.millis": 4000,
        "hazelcast.client.invocation.timeout.millis": 180000,
        "hazelcast.client.cloud.url": "https://hz.cloud",
        "hazelcast.client.statistics.enabled": true,
        "hazelcast.client.statistics.period.seconds": 4,
        "hazelcast.invalidation.reconciliation.interval.seconds": 50,
        "hazelcast.invalidation.max.tolerated.miss.count": 15,
        "hazelcast.invalidation.min.reconciliation.interval.seconds": 60,
        "hazelcast.logging.level": 3,
        "hazelcast.client.autopipelining.enabled": false,
        "hazelcast.client.autopipelining.threshold.bytes": 1024,
        "hazelcast.client.socket.no.delay": false,
        "hazelcast.client.shuffle.member.list": false
    },
    "clientLabels": [
        "label1",
        "label2"
    ],
    "network": {
        "clusterMembers": [
            "127.0.0.9",
            "127.0.0.2:5702"
        ],
        "smartRouting": false,
        "connectionTimeout": 6000,
        "ssl": {
            "enabled": true,
            "sslOptions": {
                "ca": "ca.pem",
                "cert": "cert.pem",
                "key": "key.pem",
                "servername": "foo.bar.com"
            }
        },
        "hazelcastCloud": {
            "discoveryToken": "EXAMPLE_TOKEN"
        }
    },
    "connectionStrategy": {
        "asyncStart": true,
        "reconnectMode": "async",
        "connectionRetry": {
            "initialBackoffMillis": 2000,
            "maxBackoffMillis": 60000,
            "multiplier": 3,
            "clusterConnectTimeoutMillis": 5000,
            "jitter": 0.5
        }
    },
    "serialization": {
        "defaultNumberType": "integer",
        "isBigEndian": false,
        "portableVersion": 1,
        "jsonStringDeserializationPolicy": "no_deserialization"
    },
    "nearCaches": {
        "nc-map": {
            "invalidateOnChange": false,
            "maxIdleSeconds": 2,
            "inMemoryFormat": "object",
            "timeToLiveSeconds": 3,
            "evictionPolicy": "lru",
            "evictionMaxSize": 3000,
            "evictionSamplingCount": 4,
            "evictionSamplingPoolSize": 8
        },
        "nc-map2": {
            "invalidateOnChange": false,
            "maxIdleSeconds": 2,
            "inMemoryFormat": "object",
            "timeToLiveSeconds": 3,
            "evictionPolicy": "lru",
            "evictionMaxSize": 3000,
            "evictionSamplingCount": 4,
            "evictionSamplingPoolSize": 8
        }
    },
    "reliableTopics": {
        "rt1": {
            "readBatchSize": 35,
            "overloadPolicy": "discard_newest"
        },
        "rt2": {
            "readBatchSize": 15,
            "overloadPolicy": "discard_newest"
        }
    },
    "flakeIdGenerators": {
        "flakeid": {
            "prefetchCount": 123,
            "prefetchValidityMillis": 150000
        },
        "flakeid2": {
            "prefetchCount": 1234,
            "prefetchValidityMillis": 1900000
        }
    },
    "loadBalancer": {
        "type": "random"
    }
}
